version: '3'
services:
  web:
    container_name: web
    image: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - web-network
    stdin_open: true
    tty: true
#    command:
#      - nginx
#      - -g
#      - daemon off;


#  webserver:
#    image: nginx:1.17.6-alpine
#    container_name: webserver
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - web-root:/var/www/html
#      - ./nginx-conf:/etc/nginx/conf.d
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - dhparam:/etc/ssl/certs
#    depends_on:
#      - web
#    networks:
#      - app-network
#
#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - web-root:/var/www/html
#    depends_on:
#      - webserver
#    command: certonly --webroot --webroot-path=/var/www/html --email almond.froyo@gmail.com --agree-tos --no-eff-email --staging -d almondhydroponics.com  -d www.almondhydroponics.com

volumes:
  node_modules:
#  certbot-etc:
#  certbot-var:
#  web-root:
#    driver: local
#  dhparam:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/masha/almond-re/dhparam/
#      o: bind

networks:
  web-network:
    driver: bridge
