version: '3.7'
services:
  web:
    container_name: web
    restart: unless-stopped
    build: ./
    env_file: .env

  nginx:
    container_name: nginx
    build: ./nginx
    restart: unless-stopped
    env_file: .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/ssl:/etc/ssl
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - web
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
