version: '3'
services:
  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3001'
#    command:
#      - nginx
#      - -g
#      - daemon off;
